/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.impala.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TAggregationNode implements org.apache.thrift.TBase<TAggregationNode, TAggregationNode._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TAggregationNode");

  private static final org.apache.thrift.protocol.TField GROUPING_EXPRS_FIELD_DESC = new org.apache.thrift.protocol.TField("grouping_exprs", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField AGGREGATE_EXPRS_FIELD_DESC = new org.apache.thrift.protocol.TField("aggregate_exprs", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField AGG_TUPLE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("agg_tuple_id", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField NEED_FINALIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("need_finalize", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TAggregationNodeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TAggregationNodeTupleSchemeFactory());
  }

  public List<com.cloudera.impala.thrift.TExpr> grouping_exprs; // optional
  public List<com.cloudera.impala.thrift.TExpr> aggregate_exprs; // required
  public int agg_tuple_id; // required
  public boolean need_finalize; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GROUPING_EXPRS((short)1, "grouping_exprs"),
    AGGREGATE_EXPRS((short)2, "aggregate_exprs"),
    AGG_TUPLE_ID((short)3, "agg_tuple_id"),
    NEED_FINALIZE((short)4, "need_finalize");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GROUPING_EXPRS
          return GROUPING_EXPRS;
        case 2: // AGGREGATE_EXPRS
          return AGGREGATE_EXPRS;
        case 3: // AGG_TUPLE_ID
          return AGG_TUPLE_ID;
        case 4: // NEED_FINALIZE
          return NEED_FINALIZE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __AGG_TUPLE_ID_ISSET_ID = 0;
  private static final int __NEED_FINALIZE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.GROUPING_EXPRS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GROUPING_EXPRS, new org.apache.thrift.meta_data.FieldMetaData("grouping_exprs", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.cloudera.impala.thrift.TExpr.class))));
    tmpMap.put(_Fields.AGGREGATE_EXPRS, new org.apache.thrift.meta_data.FieldMetaData("aggregate_exprs", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.cloudera.impala.thrift.TExpr.class))));
    tmpMap.put(_Fields.AGG_TUPLE_ID, new org.apache.thrift.meta_data.FieldMetaData("agg_tuple_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "TTupleId")));
    tmpMap.put(_Fields.NEED_FINALIZE, new org.apache.thrift.meta_data.FieldMetaData("need_finalize", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TAggregationNode.class, metaDataMap);
  }

  public TAggregationNode() {
  }

  public TAggregationNode(
    List<com.cloudera.impala.thrift.TExpr> aggregate_exprs,
    int agg_tuple_id,
    boolean need_finalize)
  {
    this();
    this.aggregate_exprs = aggregate_exprs;
    this.agg_tuple_id = agg_tuple_id;
    setAgg_tuple_idIsSet(true);
    this.need_finalize = need_finalize;
    setNeed_finalizeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TAggregationNode(TAggregationNode other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetGrouping_exprs()) {
      List<com.cloudera.impala.thrift.TExpr> __this__grouping_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>();
      for (com.cloudera.impala.thrift.TExpr other_element : other.grouping_exprs) {
        __this__grouping_exprs.add(new com.cloudera.impala.thrift.TExpr(other_element));
      }
      this.grouping_exprs = __this__grouping_exprs;
    }
    if (other.isSetAggregate_exprs()) {
      List<com.cloudera.impala.thrift.TExpr> __this__aggregate_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>();
      for (com.cloudera.impala.thrift.TExpr other_element : other.aggregate_exprs) {
        __this__aggregate_exprs.add(new com.cloudera.impala.thrift.TExpr(other_element));
      }
      this.aggregate_exprs = __this__aggregate_exprs;
    }
    this.agg_tuple_id = other.agg_tuple_id;
    this.need_finalize = other.need_finalize;
  }

  public TAggregationNode deepCopy() {
    return new TAggregationNode(this);
  }

  @Override
  public void clear() {
    this.grouping_exprs = null;
    this.aggregate_exprs = null;
    setAgg_tuple_idIsSet(false);
    this.agg_tuple_id = 0;
    setNeed_finalizeIsSet(false);
    this.need_finalize = false;
  }

  public int getGrouping_exprsSize() {
    return (this.grouping_exprs == null) ? 0 : this.grouping_exprs.size();
  }

  public java.util.Iterator<com.cloudera.impala.thrift.TExpr> getGrouping_exprsIterator() {
    return (this.grouping_exprs == null) ? null : this.grouping_exprs.iterator();
  }

  public void addToGrouping_exprs(com.cloudera.impala.thrift.TExpr elem) {
    if (this.grouping_exprs == null) {
      this.grouping_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>();
    }
    this.grouping_exprs.add(elem);
  }

  public List<com.cloudera.impala.thrift.TExpr> getGrouping_exprs() {
    return this.grouping_exprs;
  }

  public TAggregationNode setGrouping_exprs(List<com.cloudera.impala.thrift.TExpr> grouping_exprs) {
    this.grouping_exprs = grouping_exprs;
    return this;
  }

  public void unsetGrouping_exprs() {
    this.grouping_exprs = null;
  }

  /** Returns true if field grouping_exprs is set (has been assigned a value) and false otherwise */
  public boolean isSetGrouping_exprs() {
    return this.grouping_exprs != null;
  }

  public void setGrouping_exprsIsSet(boolean value) {
    if (!value) {
      this.grouping_exprs = null;
    }
  }

  public int getAggregate_exprsSize() {
    return (this.aggregate_exprs == null) ? 0 : this.aggregate_exprs.size();
  }

  public java.util.Iterator<com.cloudera.impala.thrift.TExpr> getAggregate_exprsIterator() {
    return (this.aggregate_exprs == null) ? null : this.aggregate_exprs.iterator();
  }

  public void addToAggregate_exprs(com.cloudera.impala.thrift.TExpr elem) {
    if (this.aggregate_exprs == null) {
      this.aggregate_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>();
    }
    this.aggregate_exprs.add(elem);
  }

  public List<com.cloudera.impala.thrift.TExpr> getAggregate_exprs() {
    return this.aggregate_exprs;
  }

  public TAggregationNode setAggregate_exprs(List<com.cloudera.impala.thrift.TExpr> aggregate_exprs) {
    this.aggregate_exprs = aggregate_exprs;
    return this;
  }

  public void unsetAggregate_exprs() {
    this.aggregate_exprs = null;
  }

  /** Returns true if field aggregate_exprs is set (has been assigned a value) and false otherwise */
  public boolean isSetAggregate_exprs() {
    return this.aggregate_exprs != null;
  }

  public void setAggregate_exprsIsSet(boolean value) {
    if (!value) {
      this.aggregate_exprs = null;
    }
  }

  public int getAgg_tuple_id() {
    return this.agg_tuple_id;
  }

  public TAggregationNode setAgg_tuple_id(int agg_tuple_id) {
    this.agg_tuple_id = agg_tuple_id;
    setAgg_tuple_idIsSet(true);
    return this;
  }

  public void unsetAgg_tuple_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __AGG_TUPLE_ID_ISSET_ID);
  }

  /** Returns true if field agg_tuple_id is set (has been assigned a value) and false otherwise */
  public boolean isSetAgg_tuple_id() {
    return EncodingUtils.testBit(__isset_bitfield, __AGG_TUPLE_ID_ISSET_ID);
  }

  public void setAgg_tuple_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __AGG_TUPLE_ID_ISSET_ID, value);
  }

  public boolean isNeed_finalize() {
    return this.need_finalize;
  }

  public TAggregationNode setNeed_finalize(boolean need_finalize) {
    this.need_finalize = need_finalize;
    setNeed_finalizeIsSet(true);
    return this;
  }

  public void unsetNeed_finalize() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NEED_FINALIZE_ISSET_ID);
  }

  /** Returns true if field need_finalize is set (has been assigned a value) and false otherwise */
  public boolean isSetNeed_finalize() {
    return EncodingUtils.testBit(__isset_bitfield, __NEED_FINALIZE_ISSET_ID);
  }

  public void setNeed_finalizeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NEED_FINALIZE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GROUPING_EXPRS:
      if (value == null) {
        unsetGrouping_exprs();
      } else {
        setGrouping_exprs((List<com.cloudera.impala.thrift.TExpr>)value);
      }
      break;

    case AGGREGATE_EXPRS:
      if (value == null) {
        unsetAggregate_exprs();
      } else {
        setAggregate_exprs((List<com.cloudera.impala.thrift.TExpr>)value);
      }
      break;

    case AGG_TUPLE_ID:
      if (value == null) {
        unsetAgg_tuple_id();
      } else {
        setAgg_tuple_id((Integer)value);
      }
      break;

    case NEED_FINALIZE:
      if (value == null) {
        unsetNeed_finalize();
      } else {
        setNeed_finalize((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GROUPING_EXPRS:
      return getGrouping_exprs();

    case AGGREGATE_EXPRS:
      return getAggregate_exprs();

    case AGG_TUPLE_ID:
      return Integer.valueOf(getAgg_tuple_id());

    case NEED_FINALIZE:
      return Boolean.valueOf(isNeed_finalize());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GROUPING_EXPRS:
      return isSetGrouping_exprs();
    case AGGREGATE_EXPRS:
      return isSetAggregate_exprs();
    case AGG_TUPLE_ID:
      return isSetAgg_tuple_id();
    case NEED_FINALIZE:
      return isSetNeed_finalize();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TAggregationNode)
      return this.equals((TAggregationNode)that);
    return false;
  }

  public boolean equals(TAggregationNode that) {
    if (that == null)
      return false;

    boolean this_present_grouping_exprs = true && this.isSetGrouping_exprs();
    boolean that_present_grouping_exprs = true && that.isSetGrouping_exprs();
    if (this_present_grouping_exprs || that_present_grouping_exprs) {
      if (!(this_present_grouping_exprs && that_present_grouping_exprs))
        return false;
      if (!this.grouping_exprs.equals(that.grouping_exprs))
        return false;
    }

    boolean this_present_aggregate_exprs = true && this.isSetAggregate_exprs();
    boolean that_present_aggregate_exprs = true && that.isSetAggregate_exprs();
    if (this_present_aggregate_exprs || that_present_aggregate_exprs) {
      if (!(this_present_aggregate_exprs && that_present_aggregate_exprs))
        return false;
      if (!this.aggregate_exprs.equals(that.aggregate_exprs))
        return false;
    }

    boolean this_present_agg_tuple_id = true;
    boolean that_present_agg_tuple_id = true;
    if (this_present_agg_tuple_id || that_present_agg_tuple_id) {
      if (!(this_present_agg_tuple_id && that_present_agg_tuple_id))
        return false;
      if (this.agg_tuple_id != that.agg_tuple_id)
        return false;
    }

    boolean this_present_need_finalize = true;
    boolean that_present_need_finalize = true;
    if (this_present_need_finalize || that_present_need_finalize) {
      if (!(this_present_need_finalize && that_present_need_finalize))
        return false;
      if (this.need_finalize != that.need_finalize)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TAggregationNode other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TAggregationNode typedOther = (TAggregationNode)other;

    lastComparison = Boolean.valueOf(isSetGrouping_exprs()).compareTo(typedOther.isSetGrouping_exprs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGrouping_exprs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.grouping_exprs, typedOther.grouping_exprs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAggregate_exprs()).compareTo(typedOther.isSetAggregate_exprs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAggregate_exprs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.aggregate_exprs, typedOther.aggregate_exprs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAgg_tuple_id()).compareTo(typedOther.isSetAgg_tuple_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAgg_tuple_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.agg_tuple_id, typedOther.agg_tuple_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNeed_finalize()).compareTo(typedOther.isSetNeed_finalize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNeed_finalize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.need_finalize, typedOther.need_finalize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TAggregationNode(");
    boolean first = true;

    if (isSetGrouping_exprs()) {
      sb.append("grouping_exprs:");
      if (this.grouping_exprs == null) {
        sb.append("null");
      } else {
        sb.append(this.grouping_exprs);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("aggregate_exprs:");
    if (this.aggregate_exprs == null) {
      sb.append("null");
    } else {
      sb.append(this.aggregate_exprs);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("agg_tuple_id:");
    sb.append(this.agg_tuple_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("need_finalize:");
    sb.append(this.need_finalize);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (aggregate_exprs == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'aggregate_exprs' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'agg_tuple_id' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'need_finalize' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TAggregationNodeStandardSchemeFactory implements SchemeFactory {
    public TAggregationNodeStandardScheme getScheme() {
      return new TAggregationNodeStandardScheme();
    }
  }

  private static class TAggregationNodeStandardScheme extends StandardScheme<TAggregationNode> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TAggregationNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GROUPING_EXPRS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.grouping_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>(_list24.size);
                for (int _i25 = 0; _i25 < _list24.size; ++_i25)
                {
                  com.cloudera.impala.thrift.TExpr _elem26; // required
                  _elem26 = new com.cloudera.impala.thrift.TExpr();
                  _elem26.read(iprot);
                  struct.grouping_exprs.add(_elem26);
                }
                iprot.readListEnd();
              }
              struct.setGrouping_exprsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // AGGREGATE_EXPRS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list27 = iprot.readListBegin();
                struct.aggregate_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>(_list27.size);
                for (int _i28 = 0; _i28 < _list27.size; ++_i28)
                {
                  com.cloudera.impala.thrift.TExpr _elem29; // required
                  _elem29 = new com.cloudera.impala.thrift.TExpr();
                  _elem29.read(iprot);
                  struct.aggregate_exprs.add(_elem29);
                }
                iprot.readListEnd();
              }
              struct.setAggregate_exprsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // AGG_TUPLE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.agg_tuple_id = iprot.readI32();
              struct.setAgg_tuple_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NEED_FINALIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.need_finalize = iprot.readBool();
              struct.setNeed_finalizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetAgg_tuple_id()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'agg_tuple_id' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetNeed_finalize()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'need_finalize' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TAggregationNode struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.grouping_exprs != null) {
        if (struct.isSetGrouping_exprs()) {
          oprot.writeFieldBegin(GROUPING_EXPRS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.grouping_exprs.size()));
            for (com.cloudera.impala.thrift.TExpr _iter30 : struct.grouping_exprs)
            {
              _iter30.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.aggregate_exprs != null) {
        oprot.writeFieldBegin(AGGREGATE_EXPRS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.aggregate_exprs.size()));
          for (com.cloudera.impala.thrift.TExpr _iter31 : struct.aggregate_exprs)
          {
            _iter31.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(AGG_TUPLE_ID_FIELD_DESC);
      oprot.writeI32(struct.agg_tuple_id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NEED_FINALIZE_FIELD_DESC);
      oprot.writeBool(struct.need_finalize);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TAggregationNodeTupleSchemeFactory implements SchemeFactory {
    public TAggregationNodeTupleScheme getScheme() {
      return new TAggregationNodeTupleScheme();
    }
  }

  private static class TAggregationNodeTupleScheme extends TupleScheme<TAggregationNode> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TAggregationNode struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.aggregate_exprs.size());
        for (com.cloudera.impala.thrift.TExpr _iter32 : struct.aggregate_exprs)
        {
          _iter32.write(oprot);
        }
      }
      oprot.writeI32(struct.agg_tuple_id);
      oprot.writeBool(struct.need_finalize);
      BitSet optionals = new BitSet();
      if (struct.isSetGrouping_exprs()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGrouping_exprs()) {
        {
          oprot.writeI32(struct.grouping_exprs.size());
          for (com.cloudera.impala.thrift.TExpr _iter33 : struct.grouping_exprs)
          {
            _iter33.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TAggregationNode struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list34 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.aggregate_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>(_list34.size);
        for (int _i35 = 0; _i35 < _list34.size; ++_i35)
        {
          com.cloudera.impala.thrift.TExpr _elem36; // required
          _elem36 = new com.cloudera.impala.thrift.TExpr();
          _elem36.read(iprot);
          struct.aggregate_exprs.add(_elem36);
        }
      }
      struct.setAggregate_exprsIsSet(true);
      struct.agg_tuple_id = iprot.readI32();
      struct.setAgg_tuple_idIsSet(true);
      struct.need_finalize = iprot.readBool();
      struct.setNeed_finalizeIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list37 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.grouping_exprs = new ArrayList<com.cloudera.impala.thrift.TExpr>(_list37.size);
          for (int _i38 = 0; _i38 < _list37.size; ++_i38)
          {
            com.cloudera.impala.thrift.TExpr _elem39; // required
            _elem39 = new com.cloudera.impala.thrift.TExpr();
            _elem39.read(iprot);
            struct.grouping_exprs.add(_elem39);
          }
        }
        struct.setGrouping_exprsIsSet(true);
      }
    }
  }

}

