/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.impala.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TCounterType implements org.apache.thrift.TEnum {
  UNIT(0),
  UNIT_PER_SECOND(1),
  CPU_TICKS(2),
  BYTES(3),
  BYTES_PER_SECOND(4),
  TIME_NS(5),
  DOUBLE_VALUE(6);

  private final int value;

  private TCounterType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TCounterType findByValue(int value) { 
    switch (value) {
      case 0:
        return UNIT;
      case 1:
        return UNIT_PER_SECOND;
      case 2:
        return CPU_TICKS;
      case 3:
        return BYTES;
      case 4:
        return BYTES_PER_SECOND;
      case 5:
        return TIME_NS;
      case 6:
        return DOUBLE_VALUE;
      default:
        return null;
    }
  }
}
