/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.impala.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TJoinOp implements org.apache.thrift.TEnum {
  INNER_JOIN(0),
  LEFT_OUTER_JOIN(1),
  LEFT_SEMI_JOIN(2),
  RIGHT_OUTER_JOIN(3),
  FULL_OUTER_JOIN(4);

  private final int value;

  private TJoinOp(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TJoinOp findByValue(int value) { 
    switch (value) {
      case 0:
        return INNER_JOIN;
      case 1:
        return LEFT_OUTER_JOIN;
      case 2:
        return LEFT_SEMI_JOIN;
      case 3:
        return RIGHT_OUTER_JOIN;
      case 4:
        return FULL_OUTER_JOIN;
      default:
        return null;
    }
  }
}
